name: Update screenshot
on: 
  workflow_dispatch:
jobs:
  screenshot:
    name: Screenshot
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:

    - name: Screenshot Website
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://erichsia7.github.io/pwdgen2/
        destination: screenshots/${{ matrix.os }}.png